name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  create-git-release:
    if: github.repository == 'jaecktec/adapter-aws-lambda'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: extract tag name
        id: tag_name
        run: |
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.SOURCE_TAG }}
          title: ${{ env.SOURCE_TAG }}

  publish-npm:
    if: github.repository == 'jaecktec/adapter-aws-lambda'
    needs: create-git-release
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # OpenID Connect token needed for provenance
      pull-requests: write # to create pull request (changesets/action)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Publish to npm
        id: changesets
        run: pnpm -r publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
